name: 백엔드 CI

on:
  pull_request:
    branches:
      - dev/be
      - develop
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: 준비 작업 디렉토리 생성
        run: mkdir -p ~/ci

      - name: 리포지토리 클론
        uses: actions/checkout@v4
        with:
          path: ~/ci/repo

      - name: H2 스프링 설정 생성
        run: |
          mkdir -p ~/ci/repo/backend/src/main/resources
          echo "spring:
            h2:
              console:
                enabled: true
                path: /h2-console
            datasource:
              url: jdbc:h2:mem:database" > ~/ci/repo/backend/src/main/resources/application.yml

      - name: 테스트 코드 실행
        run: ./gradlew test
        working-directory: ~/ci/repo

      - name: 클린업
        if: always() 
        run: rm -rf ~/ci
