name: Backend CD

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      build-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Build BootJar
        run: ./gradlew bootJar
        working-directory: ${{ env.build-directory }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-zap-jar
          path: backend/build/libs/*.jar

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: code-zap-jar
          path: ${{ secrets.WORK_DIRECTORY }}

      - name: Check Run Processes
        run: |
          pgrep_result=$(pgrep -f 'java -jar .*dev.*code-zap.*\.jar')
          IFS=' ' read -r -a pid_array <<< "$pgrep_result"
          old_run_pids="${pid_array[*]}"
          echo "RUN_PIDS=${old_run_pids}" >> $GITHUB_ENV
          echo "old_run_pids : ${{ env.RUN_PIDS }}"
        
      - name: Run Deploy Script
        run: |
          cd ${{ secrets.WORK_DIRECTORY }}
          unzip -o code-zap-jar.zip
          cd ${{ secruts.SCRIPT_DIRECTORY }}
          RUNNER_TRACKING_ID="" && bash script/start.sh dev
                    
      - name: Verify Deploy Succeed
        run: |
          sleep 2
          pgrep_result=$(pgrep -f 'java -jar .*dev.*code-zap.*\.jar')
          IFS=' ' read -r -a pid_array <<< "$pgrep_result"
          new_run_pids="${pid_array[*]}"
          echo "old_run_pids : ${{ env.RUN_PIDS }}"
          echo "new_run_pids : $new_run_pids"
          test {{ env.RUN_PIDS }} = new_run_pids && { echo "Deploy Failed"; exit 1; }
