name: Backend CD

on:
  push:
    branches:
      - develop
      - main

jobs:
  find-branch:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - name: Get current branch name
        id: get-branch
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Set environment variable based on branch
        id: set-env
        run: |
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "::set-output name=environment::prod"
          elif [ "$BRANCH_NAME" = "develop" ]; then
            echo "::set-output name=environment::dev"
          else
            echo "::set-output name=environment::staging"
          fi

  build:
    needs: find-branch
    runs-on: ubuntu-latest
    env:
      build-directory: ./backend
      ENVIRONMENT: ${{ needs.find-branch.outputs.environment }}  # Pass ENVIRONMENT to the build Job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Build BootJar
        run: ./gradlew bootJar
        working-directory: ${{ env.build-directory }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-zap-jar
          path: backend/build/libs/*.jar

  deploy:
    needs: build
    runs-on: self-hosted
    env:
      ENVIRONMENT: ${{ needs.find-branch.outputs.environment }}  # Pass ENVIRONMENT to the deploy Job
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: code-zap-jar
          path: ${{ secrets.WORK_DIRECTORY }}

      - name: Check Run Processes
        run: |
          cd ${{ secrets.SCRIPT_DIRECTORY }}
          bash check-old-pids.sh
        
      - name: Run Deploy Script
        run: |
          cd ${{ secrets.WORK_DIRECTORY }}
          unzip -o code-zap-jar.zip
          cd ${{ secrets.SCRIPT_DIRECTORY }}
          RUNNER_TRACKING_ID="" && bash start.sh ${{ env.ENVIRONMENT }}
                    
      - name: Verify Deploy Succeed
        run: |
          cd ${{ secrets.SCRIPT_DIRECTORY }}
          bash verify-deploy.sh
