name: Frontend CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  build-with-test:
    runs-on: ubuntu-latest
    env:
      frontend-directory: ./frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install
        working-directory: ${{ env.frontend-directory }}

      - name: Run Type Checking
        run: npm run tsc
        working-directory: ${{ env.frontend-directory }}

      - name: Run Tests
        run: npm run test
        working-directory: ${{ env.frontend-directory }}
